@startuml levi
    entity "TB_MEDIA_TYPES" as tbMediaTypes {
        *id: INTEGER
        Name: NVARCHAR(120)
    }

    entity "TB_GENRES" as tbGenres {
        *id: INTEGER
        Name: NVARCHAR(120)
    }

    entity "TB_PLAYLISTS" as tbPlaylists {
        *id: INTEGER
        Name: NVARCHAR(120)
    }

    entity "TB_PLAYLIST_TRACK" as tbPlaylistTrack {
        PlaylistId: INTEGER <<FK>>
        TrackId: INTEGER <<FK>>
    }

    entity "TB_TRACKS" as tbTracks {
        *id: INTEGER
        Name: NVARCHAR(200)
        AlbumId: INTEGER <<FK>>
        MediaTypeId: INTEGER <<FK>>
        GenreId: INTEGER <<FK>>
        Composer: NVARCHAR(220)
        Milliseconds: INTEGER
        Bytes: INTEGER
        UnitPrice: NUMERIC
    }

    entity "TB_ARTISTS" as tbArtists {
        *id: INTEGER
        Name: NVARCHAR(120)
    }

    entity "TB_ALBUMS" as tbAlbums {
        *id: INTEGER
        Name: NVARCHAR(120)
        ArtistId: INTEGER <<FK>>
    }

    entity "TB_INVOICES" as tbInvoices {
        *id: INTEGER
        CustomerId: INTEGER <<FK>>
        InvoiceDate: DATETIME
        BillingAddress: NVARCHAR(120)
        BillingCity: NVARCHAR(120)
    }

    entity "TB_INVOICE_ITEMS" as tbInvoiceItems {
        *id: INTEGER
        Name: NVARCHAR(120)
        InvoiceId: INTEGER <<FK>>
        TrackId: INTEGER <<FK>>
        UnitPrice: NUMERIC
        Quantity: INTEGER
    }

    entity "TB_CUSTOMERS" as tbCustomers {
        *id: INTEGER
        FirstName: NVARCHAR(40)
        LastName: NVARCHAR(20)
        Company: NVARCHAR(80)
        Address: NVARCHAR(70)
        City: NVARCHAR(40)
        State: NVARCHAR(40)
        Country: NVARCHAR(40)
        PostalCode: NVARCHAR(10)
        Phone: NVARCHAR(24)
        Fax: NVARCHAR(24)
        Email: NVARCHAR(60)
        SupportRepId: INTEGER <<FK>>
    }

    entity "TB_EMPLOYEES" as tbEmployees {
        *id: INTEGER
        FirstName: NVARCHAR(40)
        LastName: NVARCHAR(20)
        Title: NVARCHAR(30)
        ReportsTo: INTEGER
        BirthDate: DATETIME
        HireDate: DATETIME
        Address: NVARCHAR(70)
    }

    tbMediaTypes ||--o{ tbTracks
    tbTracks }o..o| tbGenres
    tbPlaylistTrack |o--|| tbPlaylists
    tbPlaylistTrack |o--|| tbTracks
    tbInvoiceItems |o--|| tbTracks
    tbTracks }o..o| tbAlbums
    tbArtists ||--o{ tbAlbums
    tbCustomers ||--o{ tbInvoices
    tbCustomers }o..o| tbEmployees
    tbEmployees }o..o| tbEmployees
@enduml